FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN ls -lh

COPY . .

# RUN python -c "while True: pass"  # Comando dummy para manter o container rodando
#CMD ["python", "-c", "while True: pass"]  # Comando dummy para teste
CMD ["python", "script-seed.py"]
